begin;

create table if not exists public.health_check_probe (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now()
);

grant usage on schema public to anon, authenticated;
grant select on public.health_check_probe to anon, authenticated;

alter table public.health_check_probe enable row level security;

drop policy if exists "Allow public read health_check_probe" on public.health_check_probe;
create policy "Allow public read health_check_probe"
  on public.health_check_probe
  for select
  to anon, authenticated
  using (true);

insert into public.health_check_probe default values;

commit;
